micronaut:
  application:
    name: natsIuppAngelo
  server:
    port: 8081
  cors:
    enabled: true

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS


nats.addresses:
- nats://localhost:4222
